
$colors = array('Maroon','Red','Pink','Brown','Orange','Apricot','Olive','Yellow','Beige','Lime','Green','Mint','Teal','Cyan','Navy','Blue','Purple','Lavender','Magenta','Black','Grey','White');

$matchwithMaroon = array('Black','Pink','Brown','Orange','Apricot','Olive','Yellow','Beige','Green','Navy','Lavender','Magenta','Grey','White')
$matchwithRed = array('Black','White','Brown','Olive','Beige','Navy','Blue','Black','Grey')
$matchwithPink = array('White','Black','Maroon','Red','Brown','Navy','Purple','Magenta')
$matchwithBrown = array('White','Red','Maroon','Olive','Black','Navy','Blue')
$matchwithOrange = array('White','Black','Red','Maroon','Olive')
$matchwithApricot = array('White','Black','Maroon',;'Olive')
$matchwithOlive = array('White','Black','Apricot','Maroon','Red','Brown','Orange','Beige','Blue','Magenta')
$matchwithYellow = array('White','Black','Green')
$matchwithBeige = array('White','Black','Maroon','Red','Olive')
$matchwithLime = array('White', Black')
$matchwithGreen = array('White','Black','Maroon','Magenta','Yellow')
$matchwithMint = array('White','Black')
$matchwithTeal = array('White','Black')
$matchwithCyan = array('White','Black')
$matchwithNavy = array('White','Black','Maroon','Red','Brown','Pink')
$matchwithBlue = array('White','Black','Purple','Lavender','Magenta','Olive','Brown','Red')
$matchwithPurple = array('White','Black','Blue','Navy')
$matchwithLavender = array('White','Black','Blue')
$matchwithMagenta = array('White','Black','Maroon','Pink','Navy','Blue','Green','Olive')
$matchwithBlack = array('White','Maroon','Red','Pink','Brown','Orange','Apricot','Olive','Yellow','Beige','Lime','Green','Mint','Teal','Cyan','Navy','Blue','Purple','Lavender','Magenta','Grey')
$matchwithGrey = array('White',';Black','Navy','Olive')
$matchwithWhite = array('White','Maroon','Red','Pink','Brown','Orange','Apricot','Olive','Yellow','Beige','Lime','Green','Mint','Teal','Cyan','Navy','Blue','Purple','Lavender','Magenta','Grey')